version: '3.8'
services:
  elasticsearch:
    build:
      context: .
      dockerfile: Dockerfile.elasticsearch
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" # 로컬 메모리 제한 (필요시 조절)
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.1
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  logstash_dev:
    image: logstash:8.11.1
    container_name: logstash_dev
    depends_on:
      - elasticsearch
    volumes:
      - ./logstash_dev/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
      - ./logstash_dev/mysql-connector-j-8.0.33.jar:/usr/share/logstash/mysql-connector-j-8.0.33.jar:ro

  logstash_prod:
    image: opensearchproject/logstash-oss-with-opensearch-output-plugin:latest
    container_name: logstash_prod
    network_mode: "host"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    environment:
      - PIPELINE_WORKERS=1
      - PIPELINE_BATCH_SIZE=100
    volumes:
      - ./logstash_prod/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
      - ./logstash_prod/mysql-connector-j-8.0.33.jar:/usr/share/logstash/mysql-connector-j-8.0.33.jar:ro