spring:
  application:
    name: deokhugam
    version: 1.0.0
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 300MB
  profiles:
    active: dev-batch   # dev, dev-batch, prod 선택 가능
  jackson:
    parser:
      allow-unquoted-control-chars: true  # 탭(code 9), 줄바꿈 등을 허용

  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        jdbc.time_zone: UTC

  resilience4j:
    retry:
      instances:
        aladinApi:
          maxAttempts: 3            # 최대 재시도 횟수
          waitDuration: 2s          # 재시도 간격
          retryExceptions: # 이 예외 발생 시 재시도
            - org.springframework.web.client.RestClientException
            - java.io.IOException
    circuitbreaker:
      instances:
        aladinApi:
          slidingWindowSize: 10
          failureRateThreshold: 50
          waitDurationInOpenState: 10s

# log
logging:
  pattern:
    console: "%d{HH:mm:ss} %-5level %logger{36} - %msg%n"
