spring:
  devtools:
    livereload:
      enabled: false
    restart:
      enabled: false
  config:
    activate:
      on-profile: dev-batch

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 020725067e5033fdf423173feba941cc
            client-secret: i5GHQUGUOdiK6CKjXjJkMbRFvYVMqstT
            redirect-uri: http://localhost:8080/api/auth/kakao/callback
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope:
              - profile_nickname
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  datasource:
    url: jdbc:mysql://localhost:3306/deokhugam-db?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: user
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate # 정합성 검증 (엔티티 vs 테이블)
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  elasticsearch:
    uris: http://localhost:9200

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
    org.hibernate.type.descriptor.sql: trace
    org.springframework.web: trace
    com.deokhugam.team4.sb12: trace