input {
  jdbc {
    jdbc_driver_library => "/usr/share/logstash/mysql-connector-j-8.0.33.jar"
    jdbc_driver_class => "com.mysql.cj.jdbc.Driver"

    jdbc_connection_string => "jdbc:mysql://host.docker.internal:3306/deokhugam-db?useSSL=false&characterEncoding=utf8"
    jdbc_user => "user"
    jdbc_password => "1234"

    lowercase_column_names => false

    statement => "SELECT
        BIN_TO_UUID(b.id) AS id,
        b.title,
        b.author,
        b.description,
        b.publisher,
        b.published_date AS publishedDate,
        b.isbn,
        b.thumbnail_key AS thumbnailKey,
        b.review_count AS reviewCount,
        b.rating,
        b.created_at AS createdAt,
        b.updated_at AS updatedAt,
        c.path AS categoryPath FROM book b LEFT JOIN book_category c ON b.book_category_id = c.id
    "
  }
}

filter {
  mutate {
    copy => { "title" => "titleSuggest" }
    add_field => { "_class" => "com.codeit.deokhugam.domain.booksearch.BookDocument" }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "books"
    document_id => "%{id}"
  }
  stdout { codec => rubydebug }
}